const fs = require('fs');
const path = require('path');

const PAGES_DIR = path.join(__dirname, 'pages');
const OUTPUT_FILE = path.join(__dirname, 'pages-data.js');

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' };

function decodeEntities(text) {
    return text.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, code) => {
        if (code[0] === '#') {
            const n = code[1].toLowerCase() === 'x' ? parseInt(code.slice(2), 16) : parseInt(code.slice(1), 10);
            return Number.isFinite(n) ? String.fromCodePoint(n) : m;
        }
        return ENTITIES[code.toLowerCase()] ?? m;
    });
}

function extractTitle(htmlContent) {
    const match = htmlContent.match(/<title[^>]*>([^<]+)<\/title>/i);
    return match ? decodeEntities(match[1].trim()) : null;
}

function getPagesData() {
    const files = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.html'));
    
    const pages = files.map(filename => {
        const filepath = path.join(PAGES_DIR, filename);
        const content = fs.readFileSync(filepath, 'utf-8');
        const title = extractTitle(content) || filename.replace('.html', '');
        
        return {
            filename,
            title
        };
    });
    
    return pages.sort((a, b) => a.filename.localeCompare(b.filename));
}

function generate() {
    const pages = getPagesData();
    
    const jsContent = `// Auto-generated by generate-pages.js - Do not edit manually
// Run 'node generate-pages.js' after adding new pages

const pagesData = ${JSON.stringify(pages, null, 4)};
`;
    
    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`Generated ${OUTPUT_FILE} with ${pages.length} pages`);
}

generate();
