const fs = require('fs');
const path = require('path');

const PAGES_DIR = path.join(__dirname, 'pages');
const OUTPUT_FILE = path.join(__dirname, 'pages-data.js');
const THUMBS_DIR = path.join(__dirname, 'thumbnails');
const MANIFEST_FILE = path.join(THUMBS_DIR, 'manifest.json');

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' };

function decodeEntities(text) {
    return text.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, code) => {
        if (code[0] === '#') {
            const n = code[1].toLowerCase() === 'x' ? parseInt(code.slice(2), 16) : parseInt(code.slice(1), 10);
            return Number.isFinite(n) ? String.fromCodePoint(n) : m;
        }
        return ENTITIES[code.toLowerCase()] ?? m;
    });
}

function extractTitle(htmlContent) {
    const match = htmlContent.match(/<title[^>]*>([^<]+)<\/title>/i);
    return match ? decodeEntities(match[1].trim()) : null;
}

function readThumbnails() {
    try {
        return JSON.parse(fs.readFileSync(MANIFEST_FILE, 'utf-8'));
    } catch {
        return {};
    }
}

function getPagesData() {
    const thumbnails = readThumbnails();
    const files = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.html'));
    
    const pages = files.map(filename => {
        const filepath = path.join(PAGES_DIR, filename);
        const content = fs.readFileSync(filepath, 'utf-8');
        const title = extractTitle(content) || filename.replace('.html', '');
        
        const entry = { filename, title };

        // Snapshot from generate-thumbnails.js; ?v= busts caches when the page changes.
        const thumb = thumbnails[filename];
        if (thumb?.hash && fs.existsSync(path.join(THUMBS_DIR, thumb.thumbnail))) {
            entry.thumbnail = `thumbnails/${encodeURIComponent(thumb.thumbnail)}?v=${thumb.hash.slice(0, 8)}`;
        }

        return entry;
    });
    
    return pages.sort((a, b) => a.filename.localeCompare(b.filename));
}

function generate() {
    const pages = getPagesData();
    
    const jsContent = `// Auto-generated by generate-pages.js - Do not edit manually
// Run 'npm run build' (or 'node generate-pages.js') after adding new pages

const pagesData = ${JSON.stringify(pages, null, 4)};
`;
    
    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`Generated ${OUTPUT_FILE} with ${pages.length} pages`);
}

generate();
