const fs = require('fs');
const path = require('path');

const PAGES_DIR = path.join(__dirname, 'pages');
const OUTPUT_FILE = path.join(__dirname, 'pages-data.js');

function extractTitle(htmlContent) {
    const match = htmlContent.match(/<title[^>]*>([^<]+)<\/title>/i);
    return match ? match[1].trim() : null;
}

function getPagesData() {
    const files = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.html'));
    
    const pages = files.map(filename => {
        const filepath = path.join(PAGES_DIR, filename);
        const content = fs.readFileSync(filepath, 'utf-8');
        const title = extractTitle(content) || filename.replace('.html', '');
        
        return {
            filename,
            title
        };
    });
    
    return pages.sort((a, b) => a.filename.localeCompare(b.filename));
}

function generate() {
    const pages = getPagesData();
    
    const jsContent = `// Auto-generated by generate-pages.js - Do not edit manually
// Run 'node generate-pages.js' after adding new pages

const pagesData = ${JSON.stringify(pages, null, 4)};
`;
    
    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`Generated ${OUTPUT_FILE} with ${pages.length} pages`);
}

generate();
