// Auto-generated by generate-pages.js - Do not edit manually
// Run 'node generate-pages.js' after adding new pages

const pagesData = [
    {
        "filename": "design-0e6b1628-b9ba-4ba9-8ebb-ca9793b72b49.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-27606911-1769-4280-af3a-aec09591c746.html",
        "title": "BIO-LINK // DANGER PROTOCOL"
    },
    {
        "filename": "design-2bd5da0e-2b67-4339-85b1-ab3cd4f78882.html",
        "title": "RED-ALERT // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-2bf5bd4a-86ed-4b53-b013-6d38689bea51.html",
        "title": "Search Header Variant"
    },
    {
        "filename": "design-305e65e3-ce70-440b-aac4-7c4c4d308b3a.html",
        "title": "AI Trace Visualizer - REPLAY MODE"
    },
    {
        "filename": "design-500863c7-8bd0-4ead-961b-d25a50b7e8ba.html",
        "title": "Sandro Kozmanishvili — Visual &amp; Digital"
    },
    {
        "filename": "design-6bfea31f-c861-42c9-bc90-5d2fcd1424a4.html",
        "title": "Header Design"
    },
    {
        "filename": "design-8461bce6-ddca-4d8d-9b48-e1c4fe5dba51.html",
        "title": "AI Trace Visualizer"
    },
    {
        "filename": "design-871d0a35-0d06-4c07-867d-cbd2feaf3214.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-b7567ae3-ebdc-4546-871e-0bce9d7dbf8e.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-c82465e8-d498-434d-858d-a0299ae7db71.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-cb0aebf5-f5df-458f-9f9a-d5f50bf49188.html",
        "title": "Fastener Search - Redesign"
    },
    {
        "filename": "design-cd7b24e4-fc9b-457c-9c34-ebd791c76545.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2"
    },
    {
        "filename": "design-e6388a10-b08c-4998-abfd-0be2d01bae2a.html",
        "title": "Search Header Redesign"
    },
    {
        "filename": "Devtool Features.html",
        "title": "Devtool Features"
    },
    {
        "filename": "Elegant Pricing.html",
        "title": "Elegant Pricing"
    },
    {
        "filename": "FoxTrove _ Operations Intelligence.html",
        "title": "FoxTrove | Operations Intelligence"
    },
    {
        "filename": "Identity Matrix Visualization.html",
        "title": "Identity Matrix Visualization"
    },
    {
        "filename": "iframe-export (1).html",
        "title": "iframe-export (1)"
    },
    {
        "filename": "iframe-export (2).html",
        "title": "iframe-export (2)"
    },
    {
        "filename": "iframe-export.html",
        "title": "iframe-export"
    },
    {
        "filename": "Linguist _ Skill Calibration.html",
        "title": "Linguist / Skill Calibration"
    },
    {
        "filename": "MANIFESTO __ KERNEL_PANIC.html",
        "title": "MANIFESTO // KERNEL_PANIC"
    },
    {
        "filename": "Metamorphic Facility Analysis.html",
        "title": "Metamorphic Facility Analysis"
    },
    {
        "filename": "NatLean _ Precision Metabolite.html",
        "title": "NatLean | Precision Metabolite"
    },
    {
        "filename": "Neural Command Center Dashboard.html",
        "title": "Neural Command Center Dashboard"
    },
    {
        "filename": "Orbital Telemetry Matrix.html",
        "title": "Orbital Telemetry Matrix"
    },
    {
        "filename": "PLANET SYNTHESIS TERMINAL.html",
        "title": "PLANET SYNTHESIS TERMINAL"
    },
    {
        "filename": "Pok_ball Technical Schematic.html",
        "title": "Pokéball Technical Schematic"
    },
    {
        "filename": "sgnl _ Lightweight Observability.html",
        "title": "sgnl | Lightweight Observability"
    },
    {
        "filename": "Spacecraft Cockpit Wireframe UI.html",
        "title": "Spacecraft Cockpit Wireframe UI"
    },
    {
        "filename": "Syntax _ Void __ Developer Agency.html",
        "title": "Syntax &amp; Void // Developer Agency"
    },
    {
        "filename": "T E R R A I N _ S Y S.html",
        "title": "T E R R A I N . S Y S"
    },
    {
        "filename": "t0 _ Architecture.html",
        "title": "t0 — Architecture"
    },
    {
        "filename": "TE-DMX _ OSC CONFIG.html",
        "title": "TE-DMX / OSC CONFIG"
    }
];
