// Auto-generated by generate-pages.js - Do not edit manually
// Run 'npm run build' (or 'node generate-pages.js') after adding new pages

const pagesData = [
    {
        "filename": "Aura _ AI Synthesis.html",
        "title": "Aura | AI Synthesis",
        "thumbnail": "thumbnails/aura-ai-synthesis-c6012b.jpg?v=3d989bd6"
    },
    {
        "filename": "design-0e6b1628-b9ba-4ba9-8ebb-ca9793b72b49.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-0e6b1628-b9ba-4ba9-8ebb-ca9793b72b49-507c81.jpg?v=9ee5b015"
    },
    {
        "filename": "design-27606911-1769-4280-af3a-aec09591c746.html",
        "title": "BIO-LINK // DANGER PROTOCOL",
        "thumbnail": "thumbnails/design-27606911-1769-4280-af3a-aec09591c746-5737ef.jpg?v=b0918319"
    },
    {
        "filename": "design-2bd5da0e-2b67-4339-85b1-ab3cd4f78882.html",
        "title": "RED-ALERT // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-2bd5da0e-2b67-4339-85b1-ab3cd4f78882-70f1fe.jpg?v=bd65d21f"
    },
    {
        "filename": "design-2bf5bd4a-86ed-4b53-b013-6d38689bea51.html",
        "title": "Search Header Variant",
        "thumbnail": "thumbnails/design-2bf5bd4a-86ed-4b53-b013-6d38689bea51-26aa53.jpg?v=8e90a0d0"
    },
    {
        "filename": "design-305e65e3-ce70-440b-aac4-7c4c4d308b3a.html",
        "title": "AI Trace Visualizer - REPLAY MODE",
        "thumbnail": "thumbnails/design-305e65e3-ce70-440b-aac4-7c4c4d308b3a-8dafb4.jpg?v=71f6c404"
    },
    {
        "filename": "design-500863c7-8bd0-4ead-961b-d25a50b7e8ba.html",
        "title": "Sandro Kozmanishvili — Visual & Digital",
        "thumbnail": "thumbnails/design-500863c7-8bd0-4ead-961b-d25a50b7e8ba-a1ade1.jpg?v=dd8e6aa4"
    },
    {
        "filename": "design-6bfea31f-c861-42c9-bc90-5d2fcd1424a4.html",
        "title": "Header Design",
        "thumbnail": "thumbnails/design-6bfea31f-c861-42c9-bc90-5d2fcd1424a4-32b025.jpg?v=39cd38df"
    },
    {
        "filename": "design-8461bce6-ddca-4d8d-9b48-e1c4fe5dba51.html",
        "title": "AI Trace Visualizer",
        "thumbnail": "thumbnails/design-8461bce6-ddca-4d8d-9b48-e1c4fe5dba51-b84ffe.jpg?v=e97ef24c"
    },
    {
        "filename": "design-871d0a35-0d06-4c07-867d-cbd2feaf3214.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-871d0a35-0d06-4c07-867d-cbd2feaf3214-537db7.jpg?v=b269dfd6"
    },
    {
        "filename": "design-b7567ae3-ebdc-4546-871e-0bce9d7dbf8e.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-b7567ae3-ebdc-4546-871e-0bce9d7dbf8e-4f18ad.jpg?v=a4968d39"
    },
    {
        "filename": "design-c82465e8-d498-434d-858d-a0299ae7db71.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-c82465e8-d498-434d-858d-a0299ae7db71-115a05.jpg?v=4b0cc84c"
    },
    {
        "filename": "design-cb0aebf5-f5df-458f-9f9a-d5f50bf49188.html",
        "title": "Fastener Search - Redesign",
        "thumbnail": "thumbnails/design-cb0aebf5-f5df-458f-9f9a-d5f50bf49188-3db4c5.jpg?v=d370f216"
    },
    {
        "filename": "design-cd7b24e4-fc9b-457c-9c34-ebd791c76545.html",
        "title": "BIO-LINK // NEURAL INTERFACE v4.0.2",
        "thumbnail": "thumbnails/design-cd7b24e4-fc9b-457c-9c34-ebd791c76545-992f83.jpg?v=98aa9780"
    },
    {
        "filename": "design-e6388a10-b08c-4998-abfd-0be2d01bae2a.html",
        "title": "Search Header Redesign",
        "thumbnail": "thumbnails/design-e6388a10-b08c-4998-abfd-0be2d01bae2a-f19d40.jpg?v=ea5b2297"
    },
    {
        "filename": "Devtool Features.html",
        "title": "Devtool Features",
        "thumbnail": "thumbnails/devtool-features-ad7481.jpg?v=bc01c88d"
    },
    {
        "filename": "DitherLab.html",
        "title": "DitherLab",
        "thumbnail": "thumbnails/ditherlab-949fb8.jpg?v=22ca8f56"
    },
    {
        "filename": "Elegant Pricing.html",
        "title": "Elegant Pricing",
        "thumbnail": "thumbnails/elegant-pricing-9663f2.jpg?v=8fe4969e"
    },
    {
        "filename": "FoxTrove _ Operations Intelligence.html",
        "title": "FoxTrove | Operations Intelligence",
        "thumbnail": "thumbnails/foxtrove-operations-intelligence-7a0d8f.jpg?v=c2ab2c45"
    },
    {
        "filename": "Grid Ripple — Studio.html",
        "title": "Grid Ripple — Studio",
        "thumbnail": "thumbnails/grid-ripple-studio-4c8fb5.jpg?v=ea0b4af4"
    },
    {
        "filename": "Identity Matrix Visualization.html",
        "title": "Identity Matrix Visualization",
        "thumbnail": "thumbnails/identity-matrix-visualization-4144c2.jpg?v=b52342cd"
    },
    {
        "filename": "iframe-export (1).html",
        "title": "iframe-export (1)",
        "thumbnail": "thumbnails/iframe-export-1-b20c5c.jpg?v=ff16e119"
    },
    {
        "filename": "iframe-export (2).html",
        "title": "iframe-export (2)",
        "thumbnail": "thumbnails/iframe-export-2-2ad1a4.jpg?v=c222fdc2"
    },
    {
        "filename": "iframe-export.html",
        "title": "iframe-export",
        "thumbnail": "thumbnails/iframe-export-e9d003.jpg?v=85d9dc1e"
    },
    {
        "filename": "KOUNTER KULTURE GENETICS.html",
        "title": "KOUNTER KULTURE GENETICS",
        "thumbnail": "thumbnails/kounter-kulture-genetics-408005.jpg?v=3a1bf126"
    },
    {
        "filename": "Linguist _ Skill Calibration.html",
        "title": "Linguist / Skill Calibration",
        "thumbnail": "thumbnails/linguist-skill-calibration-248af0.jpg?v=647fa7a2"
    },
    {
        "filename": "MANIFESTO __ KERNEL_PANIC.html",
        "title": "MANIFESTO // KERNEL_PANIC",
        "thumbnail": "thumbnails/manifesto-kernel-panic-ac0085.jpg?v=e56d3599"
    },
    {
        "filename": "Metamorphic Facility Analysis.html",
        "title": "Metamorphic Facility Analysis",
        "thumbnail": "thumbnails/metamorphic-facility-analysis-12981d.jpg?v=0b9dec43"
    },
    {
        "filename": "NatLean _ Precision Metabolite.html",
        "title": "NatLean | Precision Metabolite",
        "thumbnail": "thumbnails/natlean-precision-metabolite-86aaeb.jpg?v=3c6064be"
    },
    {
        "filename": "Neural Command Center Dashboard.html",
        "title": "Neural Command Center Dashboard",
        "thumbnail": "thumbnails/neural-command-center-dashboard-194bdb.jpg?v=f69463bd"
    },
    {
        "filename": "Orbital Telemetry Matrix.html",
        "title": "Orbital Telemetry Matrix",
        "thumbnail": "thumbnails/orbital-telemetry-matrix-0e591f.jpg?v=b1c6165a"
    },
    {
        "filename": "PLANET SYNTHESIS TERMINAL.html",
        "title": "PLANET SYNTHESIS TERMINAL",
        "thumbnail": "thumbnails/planet-synthesis-terminal-a110ca.jpg?v=9ce6d8ff"
    },
    {
        "filename": "Pok_ball Technical Schematic.html",
        "title": "Pokéball Technical Schematic",
        "thumbnail": "thumbnails/pok-ball-technical-schematic-358696.jpg?v=0129c6b8"
    },
    {
        "filename": "Project Detail_ AX-01 _ Spoormaker _ Partners.html",
        "title": "Project Detail: AX-01 | Spoormaker & Partners",
        "thumbnail": "thumbnails/project-detail-ax-01-spoormaker-partners-93a97f.jpg?v=980d0e51"
    },
    {
        "filename": "sgnl _ Lightweight Observability.html",
        "title": "sgnl | Lightweight Observability",
        "thumbnail": "thumbnails/sgnl-lightweight-observability-5300be.jpg?v=14e6eed3"
    },
    {
        "filename": "Spacecraft Cockpit Wireframe UI.html",
        "title": "Spacecraft Cockpit Wireframe UI",
        "thumbnail": "thumbnails/spacecraft-cockpit-wireframe-ui-024048.jpg?v=cd0c1c71"
    },
    {
        "filename": "Syntax _ Void __ Developer Agency.html",
        "title": "Syntax & Void // Developer Agency",
        "thumbnail": "thumbnails/syntax-void-developer-agency-4cb09f.jpg?v=f29d176f"
    },
    {
        "filename": "T E R R A I N _ S Y S.html",
        "title": "T E R R A I N . S Y S",
        "thumbnail": "thumbnails/t-e-r-r-a-i-n-s-y-s-d35897.jpg?v=1d58bac8"
    },
    {
        "filename": "t0 _ Architecture.html",
        "title": "t0 — Architecture",
        "thumbnail": "thumbnails/t0-architecture-d92520.jpg?v=b9f3325a"
    },
    {
        "filename": "TE-DMX _ OSC CONFIG.html",
        "title": "TE-DMX / OSC CONFIG",
        "thumbnail": "thumbnails/te-dmx-osc-config-3ecd4e.jpg?v=fca5a707"
    }
];
